### ISSUE TITLE
Rendering issue on some devices

### ISSUE THREAD

**Issue by Hashan11** [gregcockroft/AndroidMath#6]
I got some rendering issue on some devices. It is **not rendering at all** on some devices when I install a debug APK. (Image A) When I create a release APK, **it renders overlapped**. It's unreadable (Image B). But some devices same project working properly. (Image C)

I tried it on more than 10 devices (deferent OS, deferent model) manually and on half of them not working properly. Also I observed that same device (model) has working and not-working issue. 

Any help ?

Thanks !
Hashan.

Image A - DEBUG MODE PREVIEW (not rendering) :
![issue_debug_mode](https://user-images.githubusercontent.com/7589776/103865298-fdc3c600-50e9-11eb-8972-2880444a6b3c.jpg)
Image B - RELEASE MODE PREVIEW (overlapped) :
![issue_release_mode](https://user-images.githubusercontent.com/7589776/103865303-fef4f300-50e9-11eb-82ec-fd06a350bd2b.jpg)

Image C - WORKING PROPERLY :
![working_properly_x](https://user-images.githubusercontent.com/7589776/103866141-50ea4880-50eb-11eb-9611-2964d3107894.jpg)

(Image A and B on same device (Samsung Galaxy A01) C on Samsung Galaxy A50)

**Comment by eli-symbolab** [comment]
I have a fix for this, I will submit a PR for it soon.

In summary: the widths are not being read correctly because JNI is using Java `Int` instead of Java `Long`. This does not affect most devices, but there are some low-end devices with specific CPUs that cannot handle the discrepancy, and return `0`. This results in characters printing correctly, but not being spaced properly.

**Comment by Hashan11** [comment]
> I have a fix for this, I will submit a PR for it soon.
> 
> In summary: the widths are not being read correctly because JNI is using Java `Int` instead of Java `Long`. This does not affect most devices, but there are some low-end devices with specific CPUs that cannot handle the discrepancy, and return `0`. This results in characters printing correctly, but not being spaced properly.

Thank you very much for your reply.
Yes I thought it is JNI issue and I'm not very familiar with JNI, so I could not find the issue . In my app, I gives alternative choice _(web based rendering which is very very slow)_ for users who are not seeing this correctly. But if there is a fix it is very much appreciated ! 
**Thank you again and I'm looking for the fix** :D
