### ISSUE TITLE
java.lang.reflect.invocationtargetexception

### ISSUE THREAD

**Issue by iGuru-iOS** [gregcockroft/AndroidMath#9]
Getting target exception in the XML mentioning library <com.agog.mathdisplay.MTMathView  when compileSdkVersion and targetSdkVersion increasing to 30 and 31  may be in jcenter and maven { url "https://jitpack.io" }  is deprecated in api level 30 and 31.  Dependency is not working increasing api level please take it as a priority and fix the issue.

**Comment by uburoiubu** [comment]
Can be related to: https://github.com/gregcockroft/AndroidMath/issues/10
